services:
  - type: web
    name: pharma-sim-pro
    env: node
    plan: free
    buildCommand: "npm ci"
    startCommand: "node server.js"
    autoDeploy: true
    healthCheckPath: "/healthz"
    envVars:
      - key: NODE_ENV
        value: production
